# Generated by Django 3.2.8 on 2021-12-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hindi_translate', '0002_hinditranslatedpost_translate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hinditranslatedpost',
            old_name='translate',
            new_name='translates',
        ),
    ]
