# Generated by Django 3.2.8 on 2021-12-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindi_translate', '0007_alter_hinditranslatedpost_translate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hinditranslatedpost',
            name='translate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
