# Generated by Django 3.2.8 on 2021-12-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindi_translate', '0009_alter_hinditranslatedpost_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hinditranslatedpost',
            name='boom',
            field=models.BooleanField(default=True),
        ),
    ]
