# Generated by Django 3.2.10 on 2022-02-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hindi_translate', '0012_alter_hinditranslatedpost_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hinditranslatedpost',
            options={'get_latest_by': ['id'], 'ordering': ['-updated']},
        ),
    ]
