# Generated by Django 4.0.4 on 2022-04-19 22:29

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='full name')),
                ('photo', models.ImageField(blank=True, default='account/defaultprofileimage.jpg', upload_to='users/%Y/%m/%d', verbose_name='photo')),
                ('about', models.CharField(blank=True, max_length=150, null=True, verbose_name='about')),
                ('color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None)),
                ('lang', models.CharField(choices=[('ar', 'عربي'), ('en', 'English'), ('zh_hans', '简体中文'), ('tl', 'Filipino'), ('fr', 'français'), ('de', 'Deutsch'), ('hi', 'हिंदी'), ('id', 'bahasa Indonesia'), ('it', 'Italiana'), ('ja', '日本'), ('ko', '한국인'), ('nn', 'Norsk'), ('pt', 'Português'), ('ru', 'русский'), ('es', 'Española'), ('vi', 'Tiếng Việt'), ('bn', 'বাংলা')], default='en', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
