# Generated by Django 3.2.5 on 2021-09-29 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.FileField(upload_to='theme', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
