# Generated by Django 3.2.8 on 2021-12-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_lang'),
        ('account', '0012_merge_20211206_1816'),
    ]

    operations = [
    ]
