# Generated by Django 3.2 on 2022-04-15 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelationsScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True)),
                ('syn', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('related_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordsr', to='thesaurus.thesaurus')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='thesaurus.thesaurus')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
