# Generated by Django 3.2.8 on 2021-12-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_translate', '0002_chinesetranslatedpost_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinesetranslatedpost',
            name='boom',
            field=models.BooleanField(default=True),
        ),
    ]
