# Generated by Django 3.2.8 on 2021-12-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_translate', '0003_chinesetranslatedpost_boom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chinesetranslatedpost',
            name='boom',
        ),
    ]
