# Generated by Django 3.2.10 on 2022-02-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_translate', '0005_alter_chinesetranslatedpost_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chinesetranslatedpost',
            options={'get_latest_by': ['id'], 'ordering': ['-updated']},
        ),
    ]
