# Generated by Django 3.2.10 on 2022-04-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_translate', '0010_alter_chinesetranslatedtag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chinesetranslatedtag',
            options={'get_latest_by': ['id']},
        ),
    ]
