# Generated by Django 3.2.8 on 2021-12-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filipino_translate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filipinotranslatedpost',
            name='translate',
            field=models.BooleanField(default=True),
        ),
    ]
