# Generated by Django 3.2.10 on 2022-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutposttranslated_aboutposttranslatedtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpost',
            name='comment_active',
            field=models.BooleanField(default=True),
        ),
    ]
