# Generated by Django 3.2.10 on 2022-04-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_aboutpost_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpost',
            name='body',
            field=models.TextField(),
        ),
    ]
