# Generated by Django 3.2.10 on 2022-04-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_aboutpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpost',
            name='category',
            field=models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('about_us', 'About Us'), ('terms_and_condt', 'Term & Condt.'), ('contact_us', 'Contact Us'), ('disclaimer', 'Disclaimer'), ('cookie_policy', 'Cookie Policy')], default='c', max_length=30),
        ),
    ]
