# Generated by Django 3.2.10 on 2022-04-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_alter_language_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpost',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='languages', to='about.language'),
            preserve_default=False,
        ),
    ]
