# Generated by Django 3.2.10 on 2022-04-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_aboutpost_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpost',
            name='language',
            field=models.ForeignKey(choices=[('en', 'English'), ('ar', 'Arabic'), ('zh-hans', 'Chinese'), ('tl', 'Filipino'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('nn', 'Norwegian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('es', 'Spanish'), ('vi', 'Vietnamese')], on_delete=django.db.models.deletion.PROTECT, related_name='languages', to='about.language'),
        ),
    ]
