# Generated by Django 3.2.10 on 2022-02-27 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mytag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomtag',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tag_creators2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mycustomtag',
            name='followers',
            field=models.ManyToManyField(related_name='t_following2', through='mytag.TagContact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tagcontact',
            name='to_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_tag2', to='mytag.mycustomtag'),
        ),
        migrations.AlterField(
            model_name='tagcontact',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_from_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taggedwhatever',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs_posts_items2', to='mytag.mycustomtag'),
        ),
        migrations.AlterField(
            model_name='tagnamevalue',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_name2', to='mytag.mycustomtag'),
        ),
        migrations.AlterField(
            model_name='tagnamevalue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_tag2', to=settings.AUTH_USER_MODEL),
        ),
    ]
