# Generated by Django 4.0.4 on 2022-04-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mytag', '0003_auto_20220227_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedwhatever',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
    ]
