# Generated by Django 4.0.4 on 2022-04-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meta_description',
        ),
    ]
