# Generated by Django 3.2.5 on 2021-09-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_other_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shaid',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
