# Generated by Django 3.2.5 on 2021-10-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20211001_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='blog.publication'),
        ),
    ]
