# Generated by Django 3.2.5 on 2021-10-01 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_post_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.FileField(null=True, upload_to='publication', validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'png', 'gif'])]),
        ),
    ]
