# Generated by Django 3.2.5 on 2021-10-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20211003_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(null=True, upload_to='publication'),
        ),
    ]
