# Generated by Django 3.2.5 on 2021-10-03 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20211003_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.publication'),
        ),
    ]
