# Generated by Django 3.2.5 on 2021-10-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_post_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationcontact',
            name='to_publication',
        ),
        migrations.RemoveField(
            model_name='publicationcontact',
            name='user_from',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='PublicationContact',
        ),
    ]
