# Generated by Django 3.2.5 on 2021-10-10 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0037_sharedorotheredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedorotheredit',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='share_editor', to='auth.user'),
            preserve_default=False,
        ),
    ]
