# Generated by Django 3.2.5 on 2021-10-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0046_auto_20211015_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedwhatever',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_taggedwhatever_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taggedwhatever',
            name='object_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='object ID'),
            preserve_default=False,
        ),
    ]
