# Generated by Django 3.2.5 on 2021-10-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_alter_name_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagnamevalue',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagnamevalue',
            name='user',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='TagNameValue',
        ),
    ]
