# Generated by Django 3.2.8 on 2021-11-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_auto_20211106_0146'),
        ('blog', '0064_rename_speech_post_audio'),
    ]

    operations = [
    ]
