# Generated by Django 3.2.10 on 2022-02-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_post_scrape_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='', max_length=23),
        ),
    ]
