# Generated by Django 3.2.10 on 2022-02-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0068_auto_20220205_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='t',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
