# Generated by Django 3.2.10 on 2022-02-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_auto_20220223_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sha_256',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='sha_256'),
        ),
    ]
