# Generated by Django 3.2.10 on 2022-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0072_image_sha_256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sha_256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='sha_256'),
        ),
    ]
