# Generated by Django 3.2.10 on 2022-02-27 17:39

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('mytag', '0003_auto_20220227_2309'),
        ('blog', '0073_alter_image_sha_256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagcontact',
            name='to_tag',
        ),
        migrations.RemoveField(
            model_name='tagcontact',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='taggedwhatever',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggedwhatever',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagnamevalue',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagnamevalue',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mytag.TaggedWhatever', to='mytag.MyCustomTag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='MyCustomTag',
        ),
        migrations.DeleteModel(
            name='TagContact',
        ),
        migrations.DeleteModel(
            name='TaggedWhatever',
        ),
        migrations.DeleteModel(
            name='TagNameValue',
        ),
    ]
