# Generated by Django 3.2.10 on 2022-02-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytag', '0003_auto_20220227_2309'),
        ('blog', '0074_auto_20220227_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['id'], 'ordering': ('-publish',)},
        ),
        migrations.CreateModel(
            name='TagPostOccurrenceLen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_occurence', to='blog.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_occurrence', to='mytag.mycustomtag')),
                ('tag_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nums', to='blog.occurrence')),
            ],
        ),
    ]
