# Generated by Django 3.2.10 on 2022-03-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_auto_20220305_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.ManyToManyField(blank=True, null=True, related_name='postsource', to='blog.Sources'),
        ),
    ]
