# Generated by Django 3.2.10 on 2022-03-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_alter_post_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
