# Generated by Django 3.2.10 on 2022-03-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0004_alter_sitemap_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemap',
            old_name='slug',
            new_name='name',
        ),
    ]
