# Generated by Django 3.2.5 on 2021-08-21 19:12

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
