# Generated by Django 3.2.5 on 2021-09-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_managers'),
        ('blog', '0010_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='other_author',
            field=models.ManyToManyField(blank=True, related_name='other_authors', to='account.Profile'),
        ),
    ]
