# Generated by Django 3.2.5 on 2021-09-01 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_auto_20210902_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='other_author',
            field=models.ManyToManyField(blank=True, related_name='other_authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
