# Generated by Django 3.2.5 on 2021-09-09 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_alter_postbackup_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_editeduser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_edited', to=settings.AUTH_USER_MODEL),
        ),
    ]
