# Generated by Django 3.2.5 on 2021-10-03 01:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_publication_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='publication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 3, 1, 11, 35, 910259, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
