# Generated by Django 3.2.5 on 2021-10-14 10:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_sharedorotheredit_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=256, populate_from='title'),
        ),
    ]
