# Generated by Django 3.2.5 on 2021-10-15 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20211015_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedwhatever',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs_posts_items', to='blog.mycustomtag'),
        ),
    ]
