# Generated by Django 3.2.5 on 2021-10-15 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0043_alter_taggedwhatever_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomtag',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tag_creators', to='auth.user'),
            preserve_default=False,
        ),
    ]
