# Generated by Django 3.2.5 on 2021-10-15 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_mycustomtag_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomtag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mycustomtag',
            name='original',
            field=models.BooleanField(default=False),
        ),
    ]
