# Generated by Django 3.2.5 on 2021-10-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20211015_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedwhatever',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggedwhatever',
            name='object_id',
        ),
    ]
