# Generated by Django 3.2.5 on 2021-10-17 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_tagnamevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tags', to='blog.mycustomtag')),
            ],
        ),
        migrations.AlterField(
            model_name='tagnamevalue',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_name', to='blog.name'),
        ),
    ]
