# Generated by Django 3.2.5 on 2021-10-17 11:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0050_auto_20211017_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Names',
        ),
        migrations.RenameModel(
            old_name='TagNameValue',
            new_name='TagNameValues',
        ),
    ]
