# Generated by Django 3.2.5 on 2021-10-17 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0051_auto_20211017_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tags', to='blog.mycustomtag')),
            ],
        ),
        migrations.CreateModel(
            name='TagNameValuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_name', to='blog.namess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_tag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tagnamevalues',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagnamevalues',
            name='user',
        ),
        migrations.DeleteModel(
            name='Names',
        ),
        migrations.DeleteModel(
            name='TagNameValues',
        ),
    ]
