# Generated by Django 3.2.5 on 2021-10-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_auto_20211017_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tags', to='blog.mycustomtag')),
            ],
        ),
        migrations.RemoveField(
            model_name='tagnamevaluess',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagnamevaluess',
            name='user',
        ),
        migrations.DeleteModel(
            name='Namess',
        ),
        migrations.DeleteModel(
            name='TagNameValuess',
        ),
    ]
