# Generated by Django 3.2.5 on 2021-10-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_auto_20211017_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_tags', to='blog.mycustomtag'),
        ),
    ]
