# Generated by Django 3.2.5 on 2021-10-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_alter_name_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
