# Generated by Django 3.2.5 on 2021-10-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_tagnamevalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomtag',
            name='followers',
        ),
        migrations.DeleteModel(
            name='TagContact',
        ),
    ]
