# Generated by Django 3.2.8 on 2021-11-05 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_auto_20211106_0146'),
        ('publication', '0005_alter_publication_writer'),
        ('blog', '0061_auto_20211019_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, default='category/defaultcatg.jpg', null=True, upload_to='category/', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='account.profile', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/%Y/%m/%d', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='post',
            name='other_author',
            field=models.ManyToManyField(blank=True, related_name='other_authors', to=settings.AUTH_USER_MODEL, verbose_name='other authors'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='publication.publication', verbose_name='publication'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
    ]
