# Generated by Django 3.2.8 on 2021-11-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_auto_20211108_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='speech',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
