# Generated by Django 3.2.8 on 2021-11-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_alter_post_speech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='speech',
            new_name='audio',
        ),
    ]
