# Generated by Django 3.2.10 on 2022-01-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_merge_20211117_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scrape_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
