# Generated by Django 3.2.10 on 2022-02-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_alter_post_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='t',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
    ]
