# Generated by Django 3.2.10 on 2022-03-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0077_auto_20220317_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.ManyToManyField(blank=True, related_name='postsource', to='blog.Sources'),
        ),
    ]
