# Generated by Django 3.2.10 on 2022-04-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('russian_translate', '0007_russiantranslatedpost_g_audio_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='russiantranslatedtag',
            options={'get_latest_by': ['created']},
        ),
    ]
