# Generated by Django 3.2.5 on 2021-10-08 02:55

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('publication', '0002_publication_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='content_creater',
            new_name='writer',
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='publications_tag', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
