# Generated by Django 3.2.8 on 2021-11-08 11:48

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0005_alter_publication_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='about',
            field=models.TextField(verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(null=True, upload_to='publication', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='publications_tag', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='writer',
            field=models.ManyToManyField(related_name='publications_cc', to=settings.AUTH_USER_MODEL, verbose_name='writer'),
        ),
    ]
