# Generated by Django 3.2.8 on 2021-11-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_auto_20211106_0146'),
        ('publication', '0006_auto_20211108_1718'),
    ]

    operations = [
    ]
