# Generated by Django 3.2.5 on 2021-09-10 06:50

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('account', '0004_alter_profile_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('body', django_editorjs_fields.fields.EditorJsTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='about/images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='about_posts', to='account.profile')),
                ('tags', taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
