# Generated by Django 4.0.4 on 2022-04-19 22:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPostTranslated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='about/images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t_about_posts', to='account.profile')),
                ('tags', taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='about/images/')),
                ('category', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('about_us', 'About Us'), ('terms_and_condt', 'Term & Condt.'), ('contact_us', 'Contact Us'), ('disclaimer', 'Disclaimer'), ('cookie_policy', 'Cookie Policy')], default='c', max_length=30)),
                ('comment_active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='about_posts', to='account.profile')),
                ('tags', taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPostTranslatedTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('body', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.aboutposttranslated')),
            ],
            options={
                'verbose_name': 'about post translated Translation',
                'db_table': 'about_aboutposttranslated_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
