# Generated by Django 3.2.10 on 2022-04-08 08:20

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutpost_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpost',
            name='category',
            field=models.CharField(choices=[('p', 'p'), ('a', 'a'), ('t', 't'), ('c', 'c')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title'),
        ),
    ]
