# Generated by Django 3.2.10 on 2022-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20220408_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpost',
            name='comment_active',
            field=models.BooleanField(default=False),
        ),
    ]
