# Generated by Django 3.2.10 on 2022-04-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_aboutpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpost',
            name='category',
            field=models.CharField(choices=[('Privacy Policy', 'privacy_policy'), ('About Us', 'about_us'), ('Term & Condt.', 'terms_and_condt'), ('Contact Us', 'contact_us'), ('Disclaimer', 'disclaimer'), ('Cookie Policy', 'cookie_policy')], default='c', max_length=30),
        ),
    ]
