# Generated by Django 3.2.10 on 2022-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_aboutpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('zh-hans', 'Chinese'), ('tl', 'Filipino'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('nn', 'Norwegian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('es', 'Spanish'), ('vi', 'Vietnamese')], default='en', max_length=20)),
            ],
        ),
    ]
