# Generated by Django 3.2.10 on 2022-04-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('zh-hans', 'Chinese'), ('tl', 'Filipino'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('nn', 'Norwegian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('es', 'Spanish'), ('vi', 'Vietnamese')], max_length=20),
        ),
    ]
