# Generated by Django 3.2.10 on 2022-04-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hindi_translate', '0017_hinditranslatedpost_g_audio_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hinditranslatedtag',
            options={'get_latest_by': ['created']},
        ),
    ]
