# Generated by Django 3.2.10 on 2022-03-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemap',
            name='name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
