# Generated by Django 3.2.10 on 2022-03-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0002_sitemap_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemap',
            old_name='name',
            new_name='slug',
        ),
    ]
