# Generated by Django 3.2.5 on 2021-09-29 02:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('header', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('sidebar', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('text', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('menu', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('selected', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('hover', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('image', models.ImageField(upload_to='theme')),
            ],
        ),
    ]
