# Generated by Django 3.2.5 on 2021-09-29 03:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_theme_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='hover',
            new_name='hover_background',
        ),
        migrations.AddField(
            model_name='theme',
            name='hover_text',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
    ]
