# Generated by Django 3.2.5 on 2021-09-29 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210929_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='account.theme'),
            preserve_default=False,
        ),
    ]
