# Generated by Django 3.2.5 on 2021-10-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_my_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='account.theme'),
        ),
    ]
