# Generated by Django 3.2.8 on 2021-12-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_merge_0010_auto_20211106_0146_0010_auto_20211108_1718'),
        ('account', '0011_profile_lang'),
    ]

    operations = [
    ]
