# Generated by Django 3.2.8 on 2021-12-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.CharField(choices=[('ar', 'عربي'), ('en', 'English'), ('zh_hans', '简体中文'), ('ta', 'Filipino'), ('fr', 'français'), ('de', 'Deutsch'), ('hi', 'हिंदी'), ('id', 'bahasa Indonesia'), ('it', 'Italiana'), ('ja', '日本'), ('ko', '한국인'), ('nn', 'Norsk'), ('pt', 'Português'), ('ru', 'русский'), ('es', 'Española'), ('vi', 'Tiếng Việt')], default='en', max_length=10),
        ),
    ]
