# Generated by Django 4.0.4 on 2022-04-19 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Healthline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('news_website', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, db_index=True)),
                ('thumbnail', models.CharField(blank=True, max_length=200)),
                ('author', models.TextField(blank=True)),
                ('checker_runtime', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthlineChunksNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='HealthlineParsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('news_website', models.CharField(blank=True, max_length=3, null=True)),
                ('original_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, db_index=True, unique=True)),
                ('thumbnail', models.CharField(blank=True, max_length=200)),
                ('author', models.TextField(blank=True, null=True)),
                ('checker_runtime', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthlineChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chunk', models.TextField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='scrape.healthlinechunksnumber')),
            ],
        ),
    ]
