# Generated by Django 3.2.10 on 2022-01-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Healthline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('news_website', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, db_index=True)),
                ('thumbnail', models.CharField(blank=True, max_length=200)),
                ('author', models.TextField(blank=True)),
                ('checker_runtime', models.CharField(max_length=20)),
            ],
        ),
    ]
