# Generated by Django 3.2.10 on 2022-01-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_auto_20220120_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthline',
            name='checker_runtime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='healthline',
            name='news_website',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='NewsWebsite',
        ),
        migrations.DeleteModel(
            name='SchedulerRuntime',
        ),
    ]
