# Generated by Django 3.2.10 on 2022-01-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_auto_20220120_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthlineParsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('news_website', models.CharField(blank=True, max_length=3, null=True)),
                ('original_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, db_index=True, unique=True)),
                ('thumbnail', models.CharField(blank=True, max_length=200)),
                ('author', models.TextField(blank=True, null=True)),
                ('checker_runtime', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
