# Generated by Django 3.2.5 on 2021-10-08 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0004_alter_publication_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='writer',
            field=models.ManyToManyField(related_name='publications_cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
